// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/mozilla-services/heka/pipeline (interfaces: Plugin)

package testsupport

import ()

// An implementation of a buggy Plugin interface
type BuggyPlugin struct {
	buggy map[string]bool
}

func NewBuggyPlugin(config map[string]bool) *BuggyPlugin {
	return &BuggyPlugin{config}
}

func (b *BuggyPlugin) Init(_param0 interface{}) error {
	fail, ok := b.buggy["Init"]
	if ok && fail {
		panic("Init Failed")
	}
	return nil
}
